"""add account to blast report

Revision ID: 17ae8d2b23fc
Revises: 9d343cc9aa32
Create Date: 2024-10-22 19:22:07.462188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ae8d2b23fc'
down_revision = '9d343cc9aa32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blast_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_id', sa.Integer(), nullable=False))
        batch_op.drop_column('reseller_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('blast_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blast_report', schema=None) as batch_op:
        batch_op.drop_column('account')

    with op.batch_alter_table('blast_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reseller_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('key_id')

    # ### end Alembic commands ###
