"""rerun

Revision ID: 358c196ada9e
Revises: 870548b1ca6b
Create Date: 2024-10-14 20:25:10.463745

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "358c196ada9e"
down_revision = "870548b1ca6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_report",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("network", sa.String(length=100), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=False),
        sa.Column("month", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["api_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_report", schema=None) as batch_op:
        batch_op.create_index("apidx_user_id_month", ["user_id", "month"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_report_user_id"), ["user_id"], unique=False)

    op.create_table(
        "blast_report",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("sent_date", sa.DateTime(), nullable=False),
        sa.Column("sender", sa.String(length=100), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=False),
        sa.Column("month", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["blast_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blast_report", schema=None) as batch_op:
        batch_op.create_index("blastix_user_id_month", ["user_id", "month"], unique=False)
        batch_op.create_index(batch_op.f("ix_blast_report_user_id"), ["user_id"], unique=False)

    op.create_table(
        "email_api_report",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sent", sa.Integer(), nullable=True),
        sa.Column("failed", sa.Integer(), nullable=True),
        sa.Column("opened", sa.Integer(), nullable=True),
        sa.Column("clicked", sa.Integer(), nullable=True),
        sa.Column("bounced", sa.Integer(), nullable=True),
        sa.Column("rejected", sa.Integer(), nullable=True),
        sa.Column("complaint", sa.Integer(), nullable=True),
        sa.Column("delivered", sa.Integer(), nullable=True),
        sa.Column("month", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["api_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_api_report", schema=None) as batch_op:
        batch_op.create_index("email_apidx_user_id_month", ["user_id", "month"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_api_report_user_id"), ["user_id"], unique=False)

    op.create_table(
        "email_web_report",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sent", sa.Integer(), nullable=True),
        sa.Column("failed", sa.Integer(), nullable=True),
        sa.Column("opened", sa.Integer(), nullable=True),
        sa.Column("clicked", sa.Integer(), nullable=True),
        sa.Column("bounced", sa.Integer(), nullable=True),
        sa.Column("rejected", sa.Integer(), nullable=True),
        sa.Column("complaint", sa.Integer(), nullable=True),
        sa.Column("delivered", sa.Integer(), nullable=True),
        sa.Column("month", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["blast_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_web_report", schema=None) as batch_op:
        batch_op.create_index("email_webidx_user_id_month", ["user_id", "month"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_web_report_user_id"), ["user_id"], unique=False)

    op.create_table(
        "esme_report",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("network", sa.String(length=100), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=False),
        sa.Column("month", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["esme_client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("esme_report", schema=None) as batch_op:
        batch_op.create_index("esmeix_user_id_month", ["user_id", "month"], unique=False)
        batch_op.create_index(batch_op.f("ix_esme_report_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("esme_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_esme_report_user_id"))
        batch_op.drop_index("esmeix_user_id_month")

    op.drop_table("esme_report")
    with op.batch_alter_table("email_web_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_web_report_user_id"))
        batch_op.drop_index("email_webidx_user_id_month")

    op.drop_table("email_web_report")
    with op.batch_alter_table("email_api_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_api_report_user_id"))
        batch_op.drop_index("email_apidx_user_id_month")

    op.drop_table("email_api_report")
    with op.batch_alter_table("blast_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blast_report_user_id"))
        batch_op.drop_index("blastix_user_id_month")

    op.drop_table("blast_report")
    with op.batch_alter_table("api_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_report_user_id"))
        batch_op.drop_index("apidx_user_id_month")

    op.drop_table("api_report")
    # ### end Alembic commands ###
