"""add email report models

Revision ID: 39d6281a691d
Revises: 706d868a2e3f
Create Date: 2024-09-23 03:01:05.712502

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "39d6281a691d"
down_revision = "706d868a2e3f"
branch_labels = None
depends_on = None

service_enum = postgresql.ENUM("SMS", "EMAIL", name="service")


def upgrade():
    service_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_client", schema=None) as batch_op:
        batch_op.add_column(sa.Column("service", service_enum, nullable=True))

    with op.batch_alter_table("blast_client", schema=None) as batch_op:
        batch_op.add_column(sa.Column("service", service_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blast_client", schema=None) as batch_op:
        batch_op.drop_column("service")

    with op.batch_alter_table("api_client", schema=None) as batch_op:
        batch_op.drop_column("service")

    # ### end Alembic commands ###
    service_enum.drop(op.get_bind(), checkfirst=True)
