"""add email report models

Revision ID: 870548b1ca6b
Revises: 706d868a2e3f
Create Date: 2024-09-23 20:29:41.602389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870548b1ca6b'
down_revision = '706d868a2e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_email', sa.Boolean(), nullable=True))

    with op.batch_alter_table('blast_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_email', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blast_client', schema=None) as batch_op:
        batch_op.drop_column('has_email')

    with op.batch_alter_table('api_client', schema=None) as batch_op:
        batch_op.drop_column('has_email')

    # ### end Alembic commands ###
