"""update aid type

Revision ID: 9c0a033256ac
Revises: 1e25715410b6
Create Date: 2024-08-09 17:19:46.293086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0a033256ac'
down_revision = '1e25715410b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_client', schema=None) as batch_op:
        batch_op.alter_column('aid',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_client', schema=None) as batch_op:
        batch_op.alter_column('aid',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
