"""initial

Revision ID: 9d343cc9aa32
Revises: 
Create Date: 2024-10-15 02:25:21.836137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d343cc9aa32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_client',
    sa.Column('aid', sa.String(), nullable=False),
    sa.Column('reseller_prefix', sa.String(), nullable=True),
    sa.Column('has_email', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blast_client',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reseller_id', sa.Integer(), nullable=False),
    sa.Column('is_reseller', sa.Boolean(), nullable=False),
    sa.Column('has_email', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('esme_client',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_report',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['api_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_report', schema=None) as batch_op:
        batch_op.create_index('apidx_user_id_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_report_user_id'), ['user_id'], unique=False)

    op.create_table('blast_report',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['blast_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blast_report', schema=None) as batch_op:
        batch_op.create_index('blastix_user_id_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_blast_report_user_id'), ['user_id'], unique=False)

    op.create_table('email_api_report',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('opened', sa.Integer(), nullable=True),
    sa.Column('clicked', sa.Integer(), nullable=True),
    sa.Column('bounced', sa.Integer(), nullable=True),
    sa.Column('rejected', sa.Integer(), nullable=True),
    sa.Column('complaint', sa.Integer(), nullable=True),
    sa.Column('delivered', sa.Integer(), nullable=True),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['api_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_api_report', schema=None) as batch_op:
        batch_op.create_index('email_apidx_user_id_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_api_report_user_id'), ['user_id'], unique=False)

    op.create_table('email_web_report',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('opened', sa.Integer(), nullable=True),
    sa.Column('clicked', sa.Integer(), nullable=True),
    sa.Column('bounced', sa.Integer(), nullable=True),
    sa.Column('rejected', sa.Integer(), nullable=True),
    sa.Column('complaint', sa.Integer(), nullable=True),
    sa.Column('delivered', sa.Integer(), nullable=True),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['api_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_web_report', schema=None) as batch_op:
        batch_op.create_index('email_webidx_user_id_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_web_report_user_id'), ['user_id'], unique=False)

    op.create_table('esme_report',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['esme_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esme_report', schema=None) as batch_op:
        batch_op.create_index('esmeix_user_id_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_esme_report_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esme_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esme_report_user_id'))
        batch_op.drop_index('esmeix_user_id_month')

    op.drop_table('esme_report')
    with op.batch_alter_table('email_web_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_web_report_user_id'))
        batch_op.drop_index('email_webidx_user_id_month')

    op.drop_table('email_web_report')
    with op.batch_alter_table('email_api_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_api_report_user_id'))
        batch_op.drop_index('email_apidx_user_id_month')

    op.drop_table('email_api_report')
    with op.batch_alter_table('blast_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blast_report_user_id'))
        batch_op.drop_index('blastix_user_id_month')

    op.drop_table('blast_report')
    with op.batch_alter_table('api_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_report_user_id'))
        batch_op.drop_index('apidx_user_id_month')

    op.drop_table('api_report')
    op.drop_table('esme_client')
    op.drop_table('blast_client')
    op.drop_table('auth_user')
    op.drop_table('api_client')
    # ### end Alembic commands ###
