"""empty message

Revision ID: d22713f1083b
Revises: 
Create Date: 2024-08-10 20:07:37.791450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22713f1083b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_report',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['api_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_report', schema=None) as batch_op:
        batch_op.create_index('apidx_user_id_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_report_user_id'), ['user_id'], unique=False)

    op.create_table('blast_report',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['blast_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blast_report', schema=None) as batch_op:
        batch_op.create_index('blastix_user_id_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_blast_report_user_id'), ['user_id'], unique=False)

    op.create_table('esme_report',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['esme_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esme_report', schema=None) as batch_op:
        batch_op.create_index('esmeix_user_id_month', ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_esme_report_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esme_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esme_report_user_id'))
        batch_op.drop_index('esmeix_user_id_month')

    op.drop_table('esme_report')
    with op.batch_alter_table('blast_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blast_report_user_id'))
        batch_op.drop_index('blastix_user_id_month')

    op.drop_table('blast_report')
    with op.batch_alter_table('api_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_report_user_id'))
        batch_op.drop_index('apidx_user_id_month')

    op.drop_table('api_report')
    # ### end Alembic commands ###
