services:
  db:
    image: postgres:15-alpine
    volumes:
      - fib-pg-data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    volumes:
      - fib-redis-data:/data

  api:
    build:
      context: .
    image: fib-flask-app
    env_file:
      - .env
    command: >
      sh -c "flask db upgrade &&
            flask run --host=0.0.0.0 --port=8800 --reload"
    volumes:
      - ./app:/app
    ports:
      - "8800:8800"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    image: fib-celery
    env_file:
      - .env
    command: celery -A app.core.celery_app worker -E --loglevel=INFO
    volumes_from:
      - api
    working_dir: /
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
    image: fib-celery-beat
    env_file:
      - .env
    command: celery -A app.core.celery_app beat --loglevel=INFO
    volumes_from:
      - api
    working_dir: /
    depends_on:
      - redis

volumes:
  fib-pg-data:
  fib-redis-data:
